### ISSUE TITLE
Discord inviation link is expired.

### ISSUE THREAD

**Issue by jason19970210** [gregpr07/browser-use#13]
As the title, the discord invitation link is expired, and cannot join the group.

<img width="400" alt="Screenshot 2024-11-09 at 3 49 32 PM" src="https://github.com/user-attachments/assets/b7472ebc-fe12-431b-91ef-ba7901498e58">

Please update the link, thanks a lot !

**Comment by jason19970210** [comment]
I had made a pull request [#14](https://github.com/gregpr07/browser-use/pull/14) for updating README.md with discord invitation link.

**Comment by MagMueller** [comment]
Thank you very much !
