### ISSUE TITLE
Unable to click (or scroll to) button that's not visible on screen

### ISSUE THREAD

**Issue by tgaldes** [gregpr07/browser-use#21]
I use a website that has a dashboard with some tiles. I am prompting browser use to click on the 'Undecided' button in the Rental Applications section in the last tile. When the chrome browser is opened, this tile isn't visible because it's all the way at the bottom of the page.

The xpath of the button is filtered out by https://github.com/gregpr07/browser-use/blob/main/browser_use/dom/service.py#L205, presumably by the isVisible check.

Adding instructions such as 'scroll down to the bottom of the page and then click on ....' didn't change what actions were taken by browser use.

This is what the dashboard looks like when the button is cut off:
![Screenshot from 2024-11-16 12-44-24](https://github.com/user-attachments/assets/74e3d35e-d9c9-4042-b445-171310204928)

This is what it looks like when I've maximized the chrome window: You can see the undecided button in the bottom-most panel.
![Screenshot from 2024-11-16 12-44-38](https://github.com/user-attachments/assets/f9be5fef-707b-41ac-8fa2-71b007e30e76)

Not sure if there's an existing best practice to avoid this situation or an existing solution. On my end, I can just rearrange the tiles on the dashboard such that the button is visible when the page loads, but that won't always be the case. Maybe the fix is to support a scroll up/down action

**Comment by MagMueller** [comment]
Thank you very much just created a PR for that function #25

**Comment by MagMueller** [comment]
What did the agent output in the validation of last_action - did it realize that the button is further down?

**Comment by tgaldes** [comment]
No- it would decided to look through some of the menu buttons on the left side of the page (not pictured in the screenshots) in order to find the Undecided or New rental application button
