### ISSUE TITLE
How to run and use this with browser headless mode?

### ISSUE THREAD

**Issue by svirmi** [gregpr07/browser-use#42]
I plan to run this brilliant soft at remote server and cant.
Got an error:

`ERROR    [browser] Failed to initialize Chrome driver: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`

`Exception ignored in: <function Browser.__del__ at 0x7fbb65aa6a20>
Traceback (most recent call last):
  File "/home/zeus/miniconda3/lib/python3.13/site-packages/browser_use/browser/service.py", line 192, in __del__
    if self.driver is not None:
AttributeError: 'Browser' object has no attribute 'driver'`

I guess if I run it in headless mode this error will be gone.

How to run and use this with browser headless mode?

**Comment by gregpr07** [comment]
Hey, will address this today. We are working on switching to Playwright which makes things a little bit easier I think.

Then I will give you example of how to do that!

**Comment by NickMesser** [comment]
> Hey, will address this today. We are working on switching to Playwright which makes things a little bit easier I think.
> 
> Then I will give you example of how to do that!

Any update on this? I also would need headless mode.

**Comment by svirmi** [comment]
Issue can be closed as "headless" option added to Browser configuration.
Thank you!

**Comment by svirmi** [comment]
Issue can be closed as "headless" option added to Browser configuration.
Thank you!
