### ISSUE TITLE
[BUG] Two consecutive calls for Agent with the same Controller cases DEADLOCK + Agent is performing unexpected steps when asked to just navigate to a website

### ISSUE THREAD

**Issue by MahlerTom** [gregpr07/browser-use#50]
I created a controller externally:
```python
browser = Controller()
```

I am using it across two different calls for Agent (this is because I want to keep the entire browser open):

```python
import asyncio
from browser_use import Agent, Controller

browser = Controller(keep_open=True)

asyncio.run(
    Agent(
        task="Navigate to https://www.google.com/",
        llm="gpt-4o-mini",
        controller=browser,
    ).run(max_steps=5)
)

asyncio.run(
    Agent(
        task="Navigate to https://github.com/",
        llm="gpt-4o-mini",
        controller=browser,
    ).run(max_steps=5)
)

```

Here is the output:
```text
INFO     [agent] 🚀 Starting task: Navigate to https://www.google.com/
INFO     [agent] 
📍 Step 1
INFO     [agent] 🤷 Evaluation: Unknown
INFO     [agent] 🧠 Memory: 
INFO     [agent] 🎯 Next Goal: Navigate to Google homepage
INFO     [agent] 🛠️ Action: {"go_to_url":{"url":"https://www.google.com/"}}
INFO     [agent] 
📍 Step 2
INFO     [agent] 🤷 Evaluation: Unknown
INFO     [agent] 🧠 Memory: 
INFO     [agent] 🎯 Next Goal: Input text into the search bar
INFO     [agent] 🛠️ Action: {"input_text":{"index":7,"text":"OpenAI"}}
INFO     [agent] 📄 Result: ⌨️  Input "OpenAI" into 7: //div[1]/div[3]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/textarea[1]
INFO     [agent] 
📍 Step 3
INFO     [agent] 👍 Evaluation: Success
INFO     [agent] 🧠 Memory: Input 'OpenAI' into the search bar.
INFO     [agent] 🎯 Next Goal: Click the Google Search button to perform the search.
INFO     [agent] 🛠️ Action: {"click_element":{"index":52,"num_clicks":1}}
INFO     [agent] 📄 Result: 🖱️  Clicked element 52: //div[1]/div[3]/form[1]/div[1]/div[1]/div[2]/div[4]/div[6]/center[1]/input[1]
INFO     [agent] 
📍 Step 4
INFO     [agent] 👍 Evaluation: Success
INFO     [agent] 🧠 Memory: Searched for 'OpenAI' and received results.
INFO     [agent] 🎯 Next Goal: Click on the link to OpenAI's official website.
INFO     [agent] 🛠️ Action: {"click_element":{"index":53,"num_clicks":1}}
INFO     [agent] 📄 Result: 🖱️  Clicked element 53: //div[3]/div[1]/div[12]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/a[1]
INFO     [agent] 
📍 Step 5
INFO     [agent] 👍 Evaluation: Success
INFO     [agent] 🧠 Memory: Navigated to OpenAI's official website.
INFO     [agent] 🎯 Next Goal: Click on the 'ChatGPT' link.
INFO     [agent] 🛠️ Action: {"click_element":{"index":47,"num_clicks":1}}
INFO     [agent] 📄 Result: 🖱️  Clicked element 47: //div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/h2[1]/a[1]
INFO     [agent] ❌ Failed to complete task in maximum steps
INFO     [agent] 🚀 Starting task: Navigate to https://github.com/
INFO     [agent] 
📍 Step 1
```

Notice two different problems in this example:

1. In the first call for Agent (navigating to Google), for some reason, even though it was just supposed to navigate to Google, it decided on its own to Input text into the search bar, and search for 'OpenAI'. I have no idea why, but I suspect it's the prompt.

2. On the second call for the Agent with the browser controller, it gets stuck on step 1 and it won't continue. After debugging, I think it is a problem with the method (which is blocking):
```python
async def _get_html_content(self, with_shadow_roots: bool = True) -> str:
```
in dom/service.py

General comments:
- I have tested this code on versions 0.1.7 and 0.1.8 (which uses playwright) and they both produced the same outcome.
- I have tested this code on version 0.1.6 (which uses selenium) and only problem 1 remained (that is, on the second Agent run it was able to continue as expected).

**Comment by gregpr07** [comment]
Thanks for finding this! Will fix it asap

**Comment by gregpr07** [comment]
Hey,

1. that's weird haha - maybe openai does some magic with their model to do this, but this issue is not present if you use `ChatAnthopic` (with Claude 3.5 for example)
2. so this is an issue with `asyncio` event loops. In most cases you don't want to create more than 1 event loop per your app. When you are starting your app you should only create 1 event loop, so the implementation should be as:

```
controller = Controller()
agent1 = Agent(
	task='Navigate to https://www.google.com/',
	llm=model,
	controller=controller,
)
agent2 = Agent(
	task='Navigate to https://github.com/',
	llm=model,
	controller=controller,
)

async def main():
	await agent1.run(max_steps=3)
	await agent2.run(max_steps=3)

asyncio.run(main())
```

In special case you can't do it this way let me know. Again, in most cases 1 app = 1 event loop you reuse throughout your codebase.

**Comment by MahlerTom** [comment]
Thanks for checking it!

BTW, I also tried testing it using Azure deployment (gpt-4o and gpt-4o-mini)

I agree with you but in my case I am trying to call Agent several times with different tasks every time, like so:

```python
def _run(self, task, llm, max_steps) -> str:
        agent_history = asyncio.run(
            Agent(task=task, llm=llm, controller=self.browser).run(max_steps=max_steps)
        )

        return agent_history
```

I don't know all the tasks in advance, only in runtime and each time I call it a different task depending on different factors.

Currently, I am forced to use version 0.1.6 but I really want to upgrade to playwright.

**Comment by gregpr07** [comment]
Okay, I see. I will fix it!

Probably the best way is to separate the state from controller. (The controller just being a factory for controllers). I think that makes a lot of sense though, what you have found, thank you!

**Comment by gregpr07** [comment]
This is fixed now in https://github.com/gregpr07/browser-use/pull/80. Sorry it took a little while.

**Comment by MahlerTom** [comment]
Hi, thanks for trying to solve it!
Unfortunately, the same bug still exists.

Here is my example after modifying it to the new version (and then manually applying the fix from https://github.com/gregpr07/browser-use/pull/61 to make the steps conclude faster):


```python
import asyncio

from browser_use import Agent, Browser, BrowserConfig
from browser_use.browser.context import BrowserContext, BrowserContextConfig

llm = "gpt-4o-mini"

# Initializing the browser
browser = Browser()

# Initializing the browser context to be shared with two agents
shared_context = BrowserContext(browser=browser)

agent1 = Agent(
    task="Navigate to https://www.google.com/",
    llm=llm,
    browser_context=shared_context,
)

agent2 = Agent(
    task="Navigate to https://github.com/",
    llm=llm,
    browser_context=shared_context,
)


if __name__ == "__main__":
    asyncio.run(agent1.run())
    asyncio.run(agent2.run())
```

And here is the output:

```text
INFO     [browser_use] BrowserUse logging setup complete with level info
INFO     [agent] 🚀 Starting task: Navigate to https://www.google.com/
INFO     [agent] 
📍 Step 1
INFO     [agent] 🤷 Evaluation: Unknown
INFO     [agent] 🧠 Memory: Current URL is about:blank. Need to navigate to Google.
INFO     [agent] 🎯 Next Goal: Navigate to https://www.google.com/
INFO     [agent] 🛠️ Action: {"go_to_url":{"url":"https://www.google.com/"}}
INFO     [agent] 
📍 Step 2
INFO     [agent] 👍 Evaluation: Success
INFO     [agent] 🧠 Memory: Currently on Google homepage.
INFO     [agent] 🎯 Next Goal: Complete the task.
INFO     [agent] 🛠️ Action: {"done":{"text":"Navigated to https://www.google.com/"}}
INFO     [agent] 📄 Result: Navigated to https://www.google.com/
RESULT   [agent] Navigated to https://www.google.com/
INFO     [agent] ✅ Task completed successfully
INFO     [agent] 🚀 Starting task: Navigate to https://github.com/
INFO     [agent] 
📍 Step 1
```

Then its in a blocking state and never continues to perform step 1.

I debugged it and I can see that its blocking at `browser_use/browser/context.py` on the `BrowserContext.remove_highlights()` method at the second line `await page.evaluate(...`

I have tried a bunch of other things like using a **separate context for each agent** as you suggested in the readme (although in my usecase I need to **share one context among dynamic agents**, and I cannot use async to run them all at once (as I explained earlier):

```python
import asyncio
from browser_use import Agent, Browser, BrowserConfig
from browser_use.browser.context import BrowserContext, BrowserContextConfig

browser = Browser()

# Creating context for agent1
agent1_context = BrowserContext(browser=browser)

agent1 = Agent(
    task="Navigate to https://www.google.com/",
    llm=llm,
    browser_context=agent1_context,
)

# Creating a separate context for agent 2
agent2_context = BrowserContext(browser=browser)

agent2 = Agent(
    task="Navigate to https://github.com/",
    llm=llm,
    browser_context=agent2_context,
)

if __name__ == "__main__":
    asyncio.run(agent1.run())
    asyncio.run(agent2.run())

```

**Comment by MahlerTom** [comment]
Hi, after some more debugging I finally was able to solve it!
I couldn't have done it without your work in splitting the context and the browser, nice one!

To fix the bug I presented above we need to run asyncio like so:

```python
if _name_ == "_main_":
    asyncio.get_event_loop().run_until_complete(agent1.run())
    asyncio.get_event_loop().run_until_complete(agent2.run())
```

Then everything works
