### ISSUE TITLE
Interacting with elements within an iframe

### ISSUE THREAD

**Issue by tusharmctrl** [gregpr07/browser-use#65]
If there is interactive content within an iframe, is it not possible to interact with it programmatically?

**Comment by MagMueller** [comment]
We will support nested iframes from tomorrow on.

**Comment by gregpr07** [comment]
Fixed in version 0.1.10!!

**Comment by labidiaymen** [comment]
We’re using the TinyMCE editor inside our product. Unfortunately, it detects the toolbar but not the content area when text is written
![Image](https://github.com/user-attachments/assets/c53aab9a-16e2-4353-a89c-40a9e1e43d1a)

**Comment by MagMueller** [comment]
@labidiaymen Can you try to not use your real browser and set `disable_security=True`
